services:
  hubp:
    image: oopsunix/hubp:latest
    # image：ghcr.io/oopsunix/hubp:latest
    container_name: hubp
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:45000"
