services:
  hubp:
    image: oopsunix/hubp:latest
    # image：ghcr.io/oopsunix/hubp:latest
    container_name: hubp
    restart: unless-stopped
    volumes:
      # 挂载配置文件目录（首次启动若缺少 config.yaml 会自动生成模板）
      - ./config:/app/config
    ports:
      - "8080:45000"
